apiVersion: v1
kind: Pod
metadata:
  name: central-app
  labels:
    name: central-app
spec:
  containers:
    -
      name: mongo-central
      image: mongo:7.0
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: example
      ports:
        - containerPort: 27017
    -
      name: app-cental
      image: reljam01/bibliotekaapp:centralapp
      env:
        - name: MONGO_CONNECTION_STRING
          value: 'mongodb://root:example@localhost:27017'
      ports:
        - containerPort: 9004
