apiVersion: v1
kind: Pod
metadata:
  name: ni-app
  labels:
    name: ni-app
spec:
  containers:
    -
      name: mongo-ni
      image: mongo:7.0
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: example
      ports:
        - containerPort: 27017
    -
      name: app-ni
      image: reljam01/bibliotekaapp:librapp
      env:
        - name: MONGO_CONNECTION_STRING
          value: 'mongodb://root:example@localhost:27017'
        - name: APP_PORT
          value: 9003
      ports:
        - containerPort: 9003
