apiVersion: v1
kind: Pod
metadata:
  name: ns-app
  labels:
    name: ns-app
spec:
  hostNetwork: true
  containers:
    -
      name: mongo-ns
      image: mongo:7.0
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: example
      ports:
        - containerPort: 27017
    -
      name: app-ns
      image: reljam01/bibliotekaapp:librapp
      env:
        - name: MONGO_CONNECTION_STRING
          value: 'mongodb://root:example@localhost:27017'
        - name: APP_PORT
          value: '9001'
      ports:
        - containerPort: 9001
