name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: bibliotekaapp:nsapp
            dockerfile: nsapp/Dockerfile
            context: ./nsapp
          - image: bibliotekaapp:niapp
            dockerfile: niapp/Dockerfile
            context: ./niapp
          - image: bibliotekaapp:bgapp
            dockerfile: bgapp/Dockerfile
            context: ./bgapp
          - image: bibliotekaapp:centralapp
            dockerfile: centralapp/Dockerfile
            context: ./centralapp
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}
      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
      - 
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
