name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: bibliotekaapp/nsapp
            dockerfile: nsapp/Dockerfile
          - image: bibliotekaapp/niapp
            dockerfile: niapp/Dockerfile
          - image: bibliotekaapp/bgapp
            dockerfile: bgapp/Dockerfile
          - image: bibliotekaapp/centralapp
            dockerfile: centralapp/Dockerfile
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{env.DOCKER_USERNAME}}
          password: ${{env.DOCKER_TOKEN}}
      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
      - 
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
